const products = [
    {
        title: 'Target Progesterone',
        subtitle: 'Visual Canine Ovulation Timing Kit',
        img: 'https://storage.googleapis.com/www.inputllc.net/assets/canine-ovulation-kit-12.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 146,
        test: 12,
        group: 1,
        qty: 1,
        id: 1001,
    },
    {
        title: 'Target Progesterone',
        subtitle: 'Visual Canine Ovulation Timing Kit',
        stripeCode: 'price_1HvsdfQBWCWofh7chuJQxv19c5zB',
        price: 90,
        img: 'https://storage.googleapis.com/www.inputllc.net/assets/canine-ovulation-kit-6.jpg',
        type: 'canine',
        test: 6,
        group: 1,
        qty: 1,
        id: 1002,
    },
    {
        title: 'Blood Collection',
        subtitle: 'for Target Progesterone Kits',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/12/blood-collection-tubes-2.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 4,
        test: 12,
        group: 1,
        qty: 1,
        id: 1003,
    },
    {
        title: 'Blood Collection',
        subtitle: 'for Target Progesterone Kits',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/12/blood-collection-tubes-2.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 2,
        test: 6,
        group: 1,
        qty: 1,
        id: 1004,
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/cube-QP-CB-600x464.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 680,
        test: 10,
        group: 2,
        qty: 1,
        id: 1005,
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/cube-QP-CB-600x464.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 600,
        test: 5,
        group: 2,
        qty: 1,
        id: 1006,
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit refill',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/CB-Quick-P4-1-600x450.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 180,
        test: 10,
        group: 2,
        qty: 1,
        id: 1007,
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit refill',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/CB-Quick-P4-1-600x450.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 100,
        test: 5,
        group: 2,
        qty: 1,
        id: 1008,
    },
    {
        title: 'Relaxin Pro Canine Pregnancy Kit',
        subtitle: ' ',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/11/c-Relaxin-Pro-600x490.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 95,
        test: 5,
        group: 3,
        qty: 1,
        id: 1009,
    },
    {
        title: 'Relaxin Pro Canine Pregnancy Kit',
        subtitle: ' ',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/11/c-Relaxin-Pro-600x490.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 50,
        test: 2,
        group: 3,
        qty: 1,
        id: 1010,
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/cube-QP-EQ-100x100.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 580,
        test: 10,
        group: 4,
        qty: 1,
        id: 1011,
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/cube-QP-EQ-100x100.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 500,
        test: 5,
        group: 4,
        qty: 1,
        id: 1012,
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'Kit Refill',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/a-EQ-Quick-P4-1-600x450.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 180,
        test: 10,
        group: 4,
        qty: 1,
        id: 1013,
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'Kit Refill',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/a-EQ-Quick-P4-1-600x450.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 100,
        test: 5,
        group: 4,
        qty: 1,
        id: 1014,
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Visual-Semi-Quantitative with Color',
        img: 'https://storage.googleapis.com/www.inputllc.net/assets/igg-visual-10.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 150,
        test: 10,
        group: 5,
        qty: 1,
        id: 1015,
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Visual-Semi-Quantitative with Color',
        img: 'https://storage.googleapis.com/www.inputllc.net/assets/igg-visual-5.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 90,
        test: 5,
        group: 5,
        qty: 1,
        id: 1016,
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        img: 'https://storage.googleapis.com/www.inputllc.net/assets/igg-cube-10.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 550,
        test: 10,
        group: 5,
        qty: 1,
        id: 1017,
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        img: 'https://storage.googleapis.com/www.inputllc.net/assets/igg-cube-5.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 490,
        test: 5,
        group: 5,
        qty: 1,
        id: 1018,
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'kit refill',
        img: 'https://storage.googleapis.com/www.inputllc.net/assets/igg-refill-10.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 150,
        test: 10,
        group: 5,
        qty: 1,
        id: 1019,
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'kit refill',
        img: 'https://storage.googleapis.com/www.inputllc.net/assets/igg-refill-5.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 90,
        test: 5,
        group: 5,
        qty: 1,
        id: 1020,
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Visual-Semi-Quantitative with Color',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/Equichek-SAA-visual2-1.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 100,
        test: 5,
        group: 6,
        qty: 1,
        id: 1021,
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Visual-Semi-Quantitative with Color',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/Equichek-SAA-visual2-1.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 200,
        test: 10,
        group: 6,
        qty: 1,
        id: 1022,
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/SAA-Chek-kit-only.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 100,
        test: 5,
        group: 6,
        qty: 1,
        id: 1023,
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/SAA-Chek-kit-only.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 200,
        test: 10,
        group: 6,
        qty: 1,
        id: 1024,
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/SAA-Chek-with-cube.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 500,
        test: 5,
        group: 6,
        qty: 1,
        id: 1025,
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/SAA-Chek-with-cube.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 600,
        test: 10,
        group: 6,
        qty: 1,
        id: 1026,
    },
]

export default products;