const products = [
    {
        title: 'Target Progesterone',
        subtitle: 'Canine Ovulation Timing Kit',
        icon: 1,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/canine-ovulation-kit-12.jpg',
        type: 'canine',
        pathname: '/product-info/canine-progesterone-12',
        price: 146,
        test: 12,
        group: 1,
        qty: 1,
        id: 1001,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Target_Canine-instr.pdf', '',''],

    },
    {
        title: 'Target Progesterone',
        subtitle: 'Canine Ovulation Timing Kit',
        pathname: '/product-info/canine-progesterone-6',
        price: 90,
        icon: 1,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/canine-ovulation-kit-6.jpg',
        type: 'canine',
        test: 6,
        group: 1,
        qty: 1,
        id: 1002,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Target_Canine-instr.pdf', '',''],
    },
    {
        title: 'Blood Collection',
        subtitle: 'for Target Progesterone Kits',
        icon: 4,
        img: 'https://www.targetvet.com/wp-content/uploads/2019/12/blood-collection-tubes-2.jpg',
        type: 'canine',
        pathname: '/product-info/blood-collection-12',
        price: 4,
        test: 12,
        group: 1,
        qty: 1,
        id: 1003,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['', '',''],
    },
    {
        title: 'Blood Collection',
        subtitle: 'for Target Progesterone Kits',
        icon: 4,
        img: 'https://www.targetvet.com/wp-content/uploads/2019/12/blood-collection-tubes-2.jpg',
        type: 'canine',
        pathname: '/product-info/blood-collection-6',
        price: 2,
        test: 6,
        group: 1,
        qty: 1,
        id: 1004,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit + Cube Reader',
        icon: 3,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/canine-qp4-10-cube.jpg',
        type: 'canine',
        pathname: '/product-info/canine-quick-p4-10',
        price: 680,
        test: 10,
        group: 2,
        qty: 1,
        id: 1005,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Canine Quick P4 progesterone test is a rapid 10 min blood test to quantitate progesterone levels to get a number result using a cube reader and an RFID card standard curve (corresponding to the lot #). The Cube Reader requires three (3) batteries  CR 2032 Lithium 3V.',
        'Cube Weight (oz) 1.42',
        'Cube Dimensions L X W X H (inches) 1.5 X 1.5 X 1.5',
        'The test is based on Lateral Flow principles where the concentration of the sample is determinded by the intensity of the test line.',
        'The cassette has two lines one test and one control. A control line must always be present in a properly functioning cassette. If the control line is absent, the result is not valid.'
        ],
        highlights: ['1. Easy to use','2. Non-hemolyzed sera required for accuracy', '3. Progesterone number results in 10min', '4.  2 yr shelf life', '5. Room temperature storage',],
        productInfo: ['The kit includes 5 or 10 test cassettes, push buffer and 5-10 tips.', 'The kit does not include 10 uL pipette. This item must be purchased separately.', 'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.', 'The Sarstedt monovette blood collection product sold in accessories is recommended for blood collection for samples used on this kit.'],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Target_Canine-instr.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit + Cube Reader',
        icon: 3,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/canine-qp4-10-cube.jpg',
        type: 'canine',
        pathname: '/product-info/canine-quick-p4-5',
        price: 600,
        test: 5,
        group: 2,
        qty: 1,
        id: 1006,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Canine Quick P4 progesterone test is a rapid 10 min blood test to quantitate progesterone levels to get a number result using a cube reader and an RFID card standard curve (corresponding to the lot #). The Cube Reader requires three (3) batteries  CR 2032 Lithium 3V.',
        'Cube Weight (oz) 1.42',
        'Cube Dimensions L X W X H (inches) 1.5 X 1.5 X 1.5',
        'The test is based on Lateral Flow principles where the concentration of the sample is determinded by the intensity of the test line.',
        'The cassette has two lines one test and one control. A control line must always be present in a properly functioning cassette. If the control line is absent, the result is not valid.'
        ],
        highlights: ['1. Easy to use','2. Non-hemolyzed sera required for accuracy', '3. Progesterone number results in 10min', '4.  2 yr shelf life', '5. Room temperature storage',],
        productInfo: ['The kit includes 5 or 10 test cassettes, push buffer and 5-10 tips.', 'The kit does not include 10 uL pipette. This item must be purchased separately.', 'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.', 'The Sarstedt monovette blood collection product sold in accessories is recommended for blood collection for samples used on this kit.'],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Target_Canine-instr.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit refill',
        icon: 2,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/canine-qp4-10-refill.jpg',
        type: 'canine',
        pathname: '/product-info/canine-quick-p4-10-refill',
        price: 180,
        test: 10,
        group: 2,
        qty: 1,
        id: 1007,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Canine Quick P4 progesterone test is a rapid 10 min blood test to quantitate progesterone levels to get a number result using a cube reader and an RFID card standard curve (corresponding to the lot #). The Cube Reader requires three (3) batteries  CR 2032 Lithium 3V.',
        'Cube Weight (oz) 1.42',
        'Cube Dimensions L X W X H (inches) 1.5 X 1.5 X 1.5',
        'The test is based on Lateral Flow principles where the concentration of the sample is determinded by the intensity of the test line.',
        'The cassette has two lines one test and one control. A control line must always be present in a properly functioning cassette. If the control line is absent, the result is not valid.'
        ],
        highlights: ['1. Easy to use','2. Non-hemolyzed sera required for accuracy', '3. Progesterone number results in 10min', '4.  2 yr shelf life', '5. Room temperature storage',],
        productInfo: ['The kit includes 5 or 10 test cassettes, push buffer and 5-10 tips.', 'The kit does not include 10 uL pipette. This item must be purchased separately.', 'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.', 'The Sarstedt monovette blood collection product sold in accessories is recommended for blood collection for samples used on this kit.'],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Target_Canine-instr.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit refill',
        icon: 2,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/canine-qp4-10-refill.jpg',
        type: 'canine',
        pathname: '/product-info/canine-quick-p4-5-refill',
        price: 100,
        test: 5,
        group: 2,
        qty: 1,
        id: 1008,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Canine Quick P4 progesterone test is a rapid 10 min blood test to quantitate progesterone levels to get a number result using a cube reader and an RFID card standard curve (corresponding to the lot #). The Cube Reader requires three (3) batteries  CR 2032 Lithium 3V.',
        'Cube Weight (oz) 1.42',
        'Cube Dimensions L X W X H (inches) 1.5 X 1.5 X 1.5',
        'The test is based on Lateral Flow principles where the concentration of the sample is determinded by the intensity of the test line.',
        'The cassette has two lines one test and one control. A control line must always be present in a properly functioning cassette. If the control line is absent, the result is not valid.'
        ],
        highlights: ['1. Easy to use','2. Non-hemolyzed sera required for accuracy', '3. Progesterone number results in 10min', '4.  2 yr shelf life', '5. Room temperature storage',],
        productInfo: ['The kit includes 5 or 10 test cassettes, push buffer and 5-10 tips.', 'The kit does not include 10 uL pipette. This item must be purchased separately.', 'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.', 'The Sarstedt monovette blood collection product sold in accessories is recommended for blood collection for samples used on this kit.'],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Target_Canine-instr.pdf', '',''],
    },
    {
        title: 'Monovette',
        subtitle: '',
        icon: 4,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/20210412_121117.png',
        type: 'canine',
        pathname: '/product-info/canine-quick-p4-monovette',
        price: 10,
        test: 5,
        group: 2,
        qty: 1,
        id: 1025,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Canine Quick P4 progesterone test is a rapid 10 min blood test to quantitate progesterone levels to get a number result using a cube reader and an RFID card standard curve (corresponding to the lot #). The Cube Reader requires three (3) batteries  CR 2032 Lithium 3V.',
        'Cube Weight (oz) 1.42',
        'Cube Dimensions L X W X H (inches) 1.5 X 1.5 X 1.5',
        'The test is based on Lateral Flow principles where the concentration of the sample is determinded by the intensity of the test line.',
        'The cassette has two lines one test and one control. A control line must always be present in a properly functioning cassette. If the control line is absent, the result is not valid.'
        ],
        highlights: ['1. Easy to use','2. Non-hemolyzed sera required for accuracy', '3. Progesterone number results in 10min', '4.  2 yr shelf life', '5. Room temperature storage',],
        productInfo: ['The kit includes 5 or 10 test cassettes, push buffer and 5-10 tips.', 'The kit does not include 10 uL pipette. This item must be purchased separately.', 'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.', 'The Sarstedt monovette blood collection product sold in accessories is recommended for blood collection for samples used on this kit.'],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Target_Canine-instr.pdf', '',''],
    },
    {
        title: 'Relaxin Pro Canine Pregnancy Kit',
        subtitle: ' ',
        icon: 5,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/relaxin.png',
        type: 'canine',
        pathname: '/product-info/canine-relaxin-5',
        price: 95,
        test: 5,
        group: 3,
        qty: 1,
        id: 1009,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Canine Relaxin Pro is a 10 minute blood test used to detect pregnancy in the bitch',
        'Relaxin is a hormone which is produced by the corpus luteum when the fertilized egg implants.',
        'The test can be used ~ 21 days after breeding.',
        'The presence of two lines indicates pregnancy.',
        'A control line must always be present in a properly functioning cassette. If the control line is absent, the result is not valid.'
        ],
        highlights: ['1. Very easy to use canine pregnancy test','2. Test ~21 days post breeding', '3. Visual results in 10 min', '4.  2 yr shelf life', '5. Room temperature storage', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Relaxin-Instr.pdf', '',''],
    },
    {
        title: 'Relaxin Pro Canine Pregnancy Kit',
        subtitle: ' ',
        icon: 5,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/relaxin.png',
        type: 'canine',
        pathname: '/product-info/canine-relaxin-2',
        price: 50,
        test: 2,
        group: 3,
        qty: 1,
        id: 1010,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Canine Relaxin Pro is a 10 minute blood test used to detect pregnancy in the bitch',
        'Relaxin is a hormone which is produced by the corpus luteum when the fertilized egg implants.',
        'The test can be used ~ 21 days after breeding.',
        'The presence of two lines indicates pregnancy.',
        'A control line must always be present in a properly functioning cassette. If the control line is absent, the result is not valid.'
        ],
        highlights: ['1. Very easy to use canine pregnancy test','2. Test ~21 days post breeding', '3. Visual results in 10 min', '4.  2 yr shelf life', '5. Room temperature storage', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Relaxin-Instr.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'kit + Cube Reader',
        icon: 3,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/equine-qp4-10-cube.jpg',
        type: 'equine',
        pathname: '/product-info/equine-quick-p4-10',
        price: 580,
        test: 10,
        group: 4,
        qty: 1,
        id: 1011,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Quick-Equine-P4-with-cube-2-drops.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'kit + Cube Reader',
        icon: 3,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/equine-qp4-10-cube.jpg',
        type: 'equine',
        pathname: '/product-info/equine-quick-p4-5',
        price: 500,
        test: 5,
        group: 4,
        qty: 1,
        id: 1012,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Quick-Equine-P4-with-cube-2-drops.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'Kit Refill',
        icon: 2,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/equine-10-refill-qp4.jpg',
        type: 'equine',
        pathname: '/product-info/equine-quick-p4-10-refill',
        price: 180,
        test: 10,
        group: 4,
        qty: 1,
        id: 1013,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Quick-Equine-P4-with-cube-2-drops.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'Kit Refill',
        icon: 2,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/equine-10-refill-qp4.jpg',
        type: 'equine',
        pathname: '/product-info/equine-quick-p4-5-refill',
        price: 100,
        test: 5,
        group: 4,
        qty: 1,
        id: 1014,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Quick-Equine-P4-with-cube-2-drops.pdf', '',''],
    },
    {
        title: 'Monovette',
        subtitle: '',
        icon: 4,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/20210412_121117.png',
        type: 'canine',
        pathname: '/product-info/canine-quick-p4-monovette',
        price: 10,
        test: 5,
        group: 4,
        qty: 1,
        id: 1025,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Canine Quick P4 progesterone test is a rapid 10 min blood test to quantitate progesterone levels to get a number result using a cube reader and an RFID card standard curve (corresponding to the lot #). The Cube Reader requires three (3) batteries  CR 2032 Lithium 3V.',
        'Cube Weight (oz) 1.42',
        'Cube Dimensions L X W X H (inches) 1.5 X 1.5 X 1.5',
        'The test is based on Lateral Flow principles where the concentration of the sample is determinded by the intensity of the test line.',
        'The cassette has two lines one test and one control. A control line must always be present in a properly functioning cassette. If the control line is absent, the result is not valid.'
        ],
        highlights: ['1. Easy to use','2. Non-hemolyzed sera required for accuracy', '3. Progesterone number results in 10min', '4.  2 yr shelf life', '5. Room temperature storage',],
        productInfo: ['The kit includes 5 or 10 test cassettes, push buffer and 5-10 tips.', 'The kit does not include 10 uL pipette. This item must be purchased separately.', 'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.', 'The Sarstedt monovette blood collection product sold in accessories is recommended for blood collection for samples used on this kit.'],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Target_Canine-instr.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Semi-Quantitative with Color',
        icon: 1,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg%20pics/igg-10-visual.jpg',
        type: 'equine',
        pathname: '/product-info/equine-igg-10',
        price: 150,
        test: 10,
        group: 5,
        qty: 1,
        id: 1015,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Foal-IgG-instr-Visual-05-15-30.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Semi-Quantitative with Color',
        icon: 1,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg%20pics/igg-5-visual.jpg',
        type: 'equine',
        pathname: '/product-info/equine-igg-5',
        price: 90,
        test: 5,
        group: 5,
        qty: 1,
        id: 1016,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Foal-IgG-instr-Visual-05-15-30.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        icon: 3,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg%20pics/igg-10-cube.jpg',
        type: 'equine',
        pathname: '/product-info/equine-igg-10-quant-kit',
        price: 550,
        test: 10,
        group: 5,
        qty: 1,
        id: 1017,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Foal-IgG-instr-Visual-05-15-30.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        icon: 3,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg%20pics/igg-10-cube.jpg',
        type: 'equine',
        pathname: '/product-info/equine-igg-5-quant-kit',
        price: 490,
        test: 5,
        group: 5,
        qty: 1,
        id: 1018,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Foal-IgG-instr-Visual-05-15-30.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'kit refill',
        icon: 2,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg%20pics/igg-10-refill.jpg',
        type: 'equine',
        pathname: '/product-info/equine-igg-10-refill',
        price: 150,
        test: 10,
        group: 5,
        qty: 1,
        id: 1019,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Foal-IgG-instr-Visual-05-15-30.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'kit refill',
        icon: 2,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg%20pics/igg-10-refill.jpg',
        type: 'equine',
        pathname: '/product-info/equine-igg-5-refill',
        price: 90,
        test: 5,
        group: 5,
        qty: 1,
        id: 1020,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/Foal-IgG-instr-Visual-05-15-30.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Semi-Quantitative with Color',
        icon: 1,
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/Equichek-SAA-visual2-1.jpg',
        type: 'equine',
        pathname: '/product-info/equine-saa-10',
        price: 200,
        test: 10,
        group: 6,
        qty: 1,
        id: 1022,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/EquiCheck-instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Semi-Quantitative with Color',
        icon: 1,
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/Equichek-SAA-visual2-1.jpg',
        type: 'equine',
        pathname: '/product-info/equine-saa-5',
        price: 100,
        test: 5,
        group: 6,
        qty: 1,
        id: 1021,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/EquiCheck-instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        icon: 3,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/saa-10-cube.jpg',
        type: 'equine',
        pathname: '/product-info/equine-saa-10-quant-kit-cube',
        price: 600,
        test: 10,
        group: 6,
        qty: 1,
        id: 1026,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/EquiCheck-instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        icon: 3,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/saa-5-cube.jpg',
        type: 'equine',
        pathname: '/product-info/equine-saa-5-quant-kit-cube',
        price: 500,
        test: 5,
        group: 6,
        qty: 1,
        id: 1025,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.', 'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.', 'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.', 'The Sarstedt monovette blood collection product sold in accessories is recommended for blood collection for samples used on this kit.'],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/EquiCheck-instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'refill Kit',
        icon: 2,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/saa-10-refill.jpg',
        type: 'equine',
        pathname: '/product-info/equine-saa-10-quant-kit',
        price: 200,
        test: 10,
        group: 6,
        qty: 1,
        id: 1024,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/EquiCheck-instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'refill Kit',
        icon: 2,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/saa-5-refill.jpg',
        type: 'equine',
        pathname: '/product-info/equine-saa-5-quant-kit',
        price: 100,
        test: 5,
        group: 6,
        qty: 1,
        id: 1023,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        productInfo: [''],
        disclaimer: 'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        instructions: ['https://storage.googleapis.com/www.inputllc.net/TargetVet%20PDF%20instructions/EquiCheck-instructions.pdf', '',''],
    },
]

export default products;