const products = [
    {
        title: 'Target Progesterone',
        subtitle: 'Visual Canine Ovulation Timing Kit',
        img: 'https://storage.googleapis.com/www.inputllc.net/products/canine-ovulation-kit-12.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 146,
        test: 12,
        group: 1,
        qty: 1,
        id: 1001,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Target Progesterone',
        subtitle: 'Visual Canine Ovulation Timing Kit',
        stripeCode: 'price_1HvsdfQBWCWofh7chuJQxv19c5zB',
        price: 90,
        img: 'https://storage.googleapis.com/www.inputllc.net/products/canine-ovulation-kit-6.jpg',
        type: 'canine',
        test: 6,
        group: 1,
        qty: 1,
        id: 1002,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Blood Collection',
        subtitle: 'for Target Progesterone Kits',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/12/blood-collection-tubes-2.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 4,
        test: 12,
        group: 1,
        qty: 1,
        id: 1003,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Blood Collection',
        subtitle: 'for Target Progesterone Kits',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/12/blood-collection-tubes-2.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 2,
        test: 6,
        group: 1,
        qty: 1,
        id: 1004,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/cube-QP-CB-600x464.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 680,
        test: 10,
        group: 2,
        qty: 1,
        id: 1005,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/cube-QP-CB-600x464.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 600,
        test: 5,
        group: 2,
        qty: 1,
        id: 1006,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit refill',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/CB-Quick-P4-1-600x450.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 180,
        test: 10,
        group: 2,
        qty: 1,
        id: 1007,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Canine Ovulation Timing Kit',
        subtitle: 'kit refill',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/CB-Quick-P4-1-600x450.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 100,
        test: 5,
        group: 2,
        qty: 1,
        id: 1008,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Relaxin Pro Canine Pregnancy Kit',
        subtitle: ' ',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/11/c-Relaxin-Pro-600x490.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 95,
        test: 5,
        group: 3,
        qty: 1,
        id: 1009,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Relaxin Pro Canine Pregnancy Kit',
        subtitle: ' ',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/11/c-Relaxin-Pro-600x490.jpg',
        type: 'canine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 50,
        test: 2,
        group: 3,
        qty: 1,
        id: 1010,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/cube-QP-EQ-100x100.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 580,
        test: 10,
        group: 4,
        qty: 1,
        id: 1011,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/cube-QP-EQ-100x100.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 500,
        test: 5,
        group: 4,
        qty: 1,
        id: 1012,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'Kit Refill',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/a-EQ-Quick-P4-1-600x450.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 180,
        test: 10,
        group: 4,
        qty: 1,
        id: 1013,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Quick P4 / Cube Quantitative Equine Progesterone Kit',
        subtitle: 'Kit Refill',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/a-EQ-Quick-P4-1-600x450.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 100,
        test: 5,
        group: 4,
        qty: 1,
        id: 1014,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Visual-Semi-Quantitative with Color',
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg-visual-10.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 150,
        test: 10,
        group: 5,
        qty: 1,
        id: 1015,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Visual-Semi-Quantitative with Color',
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg-visual-5.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 90,
        test: 5,
        group: 5,
        qty: 1,
        id: 1016,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg-cube-10.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 550,
        test: 10,
        group: 5,
        qty: 1,
        id: 1017,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg-cube-5.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 490,
        test: 5,
        group: 5,
        qty: 1,
        id: 1018,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'kit refill',
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg-refill-10.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 150,
        test: 10,
        group: 5,
        qty: 1,
        id: 1019,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'Equine Immuno-Chek G Foal IgG Kit',
        subtitle: 'kit refill',
        img: 'https://storage.googleapis.com/www.inputllc.net/products/igg-refill-5.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 90,
        test: 5,
        group: 5,
        qty: 1,
        id: 1020,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Visual-Semi-Quantitative with Color',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/Equichek-SAA-visual2-1.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 100,
        test: 5,
        group: 6,
        qty: 1,
        id: 1021,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Visual-Semi-Quantitative with Color',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/Equichek-SAA-visual2-1.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 200,
        test: 10,
        group: 6,
        qty: 1,
        id: 1022,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/SAA-Chek-kit-only.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 100,
        test: 5,
        group: 6,
        qty: 1,
        id: 1023,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/SAA-Chek-kit-only.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 200,
        test: 10,
        group: 6,
        qty: 1,
        id: 1024,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/SAA-Chek-with-cube.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 500,
        test: 5,
        group: 6,
        qty: 1,
        id: 1025,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
    {
        title: 'EquiChek™ SAA Kit',
        subtitle: 'Quantitative Kit + Cube Reader',
        img: 'https://www.targetvet.com/wp-content/uploads/2019/10/SAA-Chek-with-cube.jpg',
        type: 'equine',
        stripeCode: 'price_1HvsdfQBWCWoh7chuJQxv19c5zB',
        price: 600,
        test: 10,
        group: 6,
        qty: 1,
        id: 1026,
        info: ['The kit includes 6 or 12 test cups, 2 Wash reagents, Enzyme, Substrate A & B, a mixing bottle and sample pipettes.',
        'Target kit is shipped without ice by 2 day express. Upon receipt, the kit is refrigerated to have the shelf life on the box. The kit has very good stability and we want to minimize environmental impact by eliminating the use of single use styrofoam packaging in our shipping materials.',
        'Alternately instead of storing the entire kit in refrigerator, ONLY the Substrate B and Enzyme solutions needs to be Refrigerated and all other KIT components including the cups can be stored at Room temperature. This means the kit and reagents are quickly ready whenever needed for testing- rather than waiting for possibly 1 hr for cups to come to room temperature.',
        'The kit does not include blood collection tubes, syringes, or needles. These items must be purchased separately if needed.',
        'Intended for veterinary use only. Not for human use. The manufacturer warrants the kit for its intended use. BioMetallics’ liability is limited to the value of the kit.',
        ],
        description: ['The Target Canine progesterone test is a rapid 9 min blood test to determine progesterone levels based on visual color changes of the test cup from bright blue to white.',
        'The test is based on ELISA principles where the sample and reagents are filtered through the antibody on the porous test cup. The accuracy of the test is based on a highly specific antibody which is trapped in the porous cup matrix.',
        'The test detects the initial rise in progesterone to accurately predict ovulation in the bitch to determine optimal breeding dates.',
        'The test detects a drop in progesterone at the end of the pregnancy to signal normal whelping within 24 hours to time a C-section accurately.',
        ],
        highlights: ['1. Very easy to use blood test','2. Million tests used worldwide', '3. Very reliable and accurate', '4.  1 yr shelf life – refrigerate upon receipt', '5. Visual semi-quantitative results in 9 min', '6. Color chart for progesterone number range'],
        instructions: ['instructions.pdf', '',''],
    },
]

export default products;